name: Python package build and publish

on: [push, pull_request]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@v2
      with:
        repository: 'https://github.com/cyberduckninja/RocketJoe.git'
        #ref: '2b3956be9e6363c57a8b814464e65fb052a36433'

    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        sudo apt-get update \
        && sudo apt-get install -y  python3-dev
        python -m pip install --upgrade pip
        pip install twine flake8 conan
        conan user
        conan remote add bincrafters https://api.bintray.com/conan/bincrafters/public-conan
        conan remote add jinncrafters https://api.bintray.com/conan/jinncrafters/conan

    - name: Lint with flake8 for syntax errors
      run: |
        pip install flake8
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

    - name: Build manylinux Python wheels
      uses: RalfG/python-wheels-manylinux-build@v0.2.2-manylinux2010_x86_64
      with:
        python-versions: 'cp36-cp36m cp37-cp37m'
        build-requirements: 'cython numpy'
        system-packages: 'lrzip-devel zlib-devel'
        package-path: ''
        pip-wheel-args: '--no-deps'
    #- name: Publish wheels to PyPI
    #  env:
    #    TWINE_USERNAME: ${{ secrets.PYPI_USERNAME }}
    #    TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
      #run: |
      #  twine upload wheelhouse/*-manylinux*.whl
